name: ecommerce_app
description: A customer mobile app for e-commerce.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.14.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo/logo.png"
